name: Streamlit update (empty github commit)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
    # Daily at 3pm

permissions:
  contents: write
  
jobs:
  Empty_commit_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repo
      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Make Empty Commit
        run: git commit --allow-empty -m "Empty-Commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
