name: four_day_qdrant_check

on:
  schedule:
    - cron: '13 */96 * * *'
    # “At minute 13 past every 96th hour.” https://crontab.guru/#13_*/96_*_*_*
  workflow_dispatch:  # enables ability to run manually 
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Run qdrant_check.py
        env:
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        run: python qdrant_check.py