name: Check services each Mon and Fri

on:
  schedule:
    - cron: '0 13 * * 1,5'
    # GitHub's scheduler runs jobs on a fixed daily or weekly schedule. 
    # This runs at 13:00 on every Monday and Friday
  workflow_dispatch:  # enables ability to run manually 

jobs:
  check_services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3
        run: sudo apt-get install python3

      - name: Install qdrant dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install qdrant_client

      - name: Check Qdrant Status
        env:
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        run: python qdrant_check.py

      - name: Check Streamlit Status
        run: |
          python -m pip install requests
          python streamlit_check.py
