name: Services check

on:
  schedule:
    - cron: '0 13 * * 1,5'
    # GitHub's scheduler runs jobs on a fixed daily or weekly schedule. 
    # This runs at 13:00 on every Monday and Friday
  workflow_dispatch:  # enables ability to run manually 

jobs:
  check_services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install qdrant dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install qdrant_client
          python -m pip install selenium webdriver-manager

      - name: Check Qdrant Status
        env:
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        run: python qdrant_check.py

      - name: Install Chrome to Preview Strreamlit UI
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Check Streamlit Status
        run: python streamlit_ui_check.py
